name: beautina_provider
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.0+21

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # provider: 3.2.0
  flare_flutter: ^3.0.2
  firebase_auth: ^3.11.2
  flutter_screenutil: ^5.3.1
  google_sign_in: ^5.2.4
  fluttertoast: ^8.0.9
  community_material_icon: ^5.9.55
  bot_toast: ^4.0.1
  package_info: ^2.0.2
  google_fonts: ^2.3.1
  flutter_rounded_date_picker: ^2.0.2
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  timeago: ^3.2.2
  connectivity: ^3.0.6
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.2.0
  # city_picker: ^0.1.4
  # flutter_cupertino_date_picker: ^1.0.8
  flutter_picker: ^2.0.3
  rflutter_alert: ^2.0.4
  firebase_messaging: ^11.2.11	
  url_launcher: ^6.0.20
  firebase_remote_config: ^2.0.2
  page_transition: ^2.0.5
  # rating_bar: ^0.2.0
  spring_button: ^2.0.0
  # dropdownfield: ^1.0.3
  # geolocator: ^5.1.1+1
  rating_bar_flutter: ^1.0.2

  cloud_firestore: ^3.1.10
  table_calendar: ^3.0.5
  # image_picker: ^0.8.4+11
  # image_picker_modern: ^0.4.12+3
  rounded_loading_button: ^2.1.0
  geolocator: ^8.2.0
  # credit_card: ^0.1.8
  clay_containers: ^0.3.2
  preload_page_view: ^0.1.6
  # flutter_launcher_icons: ^0.9.2
  # home_indicator: ^2.0.0
  # apple_sign_in: ^0.1.0
  flutter_cache_manager: ^3.3.0
  # google_fonts_arabic: ^1.1.7
  # dio_http_cache: ^0.3.0 
  # dio: ^4.0.5 
  modal_bottom_sheet: ^2.0.1
  # flutter_duration_picker: ^1.0.4
  keyboard_actions: ^3.4.7
  # flutter_picker_view: ^1.1.0
  # steps: ^1.0.1
  fluttericon: ^2.0.0
  # firebase_dynamic_links: ^4.1.1
  firebase_storage: ^10.2.9   
  firebase_image: ^1.1.1
  share: ^2.0.4	
  clipboard: ^0.1.3
  regexpattern: ^2.0.1
  readmore: ^2.1.0
  emojis: ^0.9.9
  ndialog: ^4.1.1
  scrollable_list_tabview: ^0.2.0-nullsafety
  shimmer: ^2.0.0
  # the_apple_sign_in: ^1.1.1
  firebase_core: ^1.13.1
  get_it: ^7.2.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  google_sign_in_web: ^0.10.0+5
  sign_in_with_apple: ^4.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  flutter_firebase_chat_core:
    git:
     url: https://github.com/dev313m/flutter_firebase_chat_core.git
  
  flutter_chat_ui: ^1.5.8
  flutter_chat_types: ^3.3.4
  flutter_link_previewer: ^2.6.6
  http: ^0.13.4
  image_picker: ^0.8.5
  mime: ^1.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.9
  file_picker: ^4.5.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/iwow.png"
  adaptive_icon_background: "assets/icons/iwow.png"
  adaptive_icon_foreground: "assets/icons/iwow.png"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/services_icons/
   - assets/images/test.jpg
   - assets/rive/waiting.flr
   - assets/rive/bg.flr
   - assets/rive/goodone.flr
   - assets/rive/salon.flr
   - assets/rive/internet.flr
   - assets/rive/noconnection.flr
   - assets/rive/upgrade.flr
   - assets/rive/background2.flr
   - assets/rive/favoritebg.flr
   - assets/rive/amazing.flr
   - assets/rive/bulb.flr
   - assets/images/default.png
   - assets/images/gift.png
   - assets/rive/night.flr
   - assets/rive/notification.flr
   - assets/rive/lock.flr
   - assets/rive/error.flr
   - assets/rive/share.flr
   - assets/rive/gift.flr
   - assets/rive/rocket.flr
   - assets/rive/load.flr
   - assets/images/50.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          # style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
